# Generated by Django 4.2.3 on 2023-07-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='rasmlar/'),
        ),
        migrations.DeleteModel(
            name='BlogImages',
        ),
    ]
